CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(100),
                                     email VARCHAR(50) NOT NULL,
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- CREATE TABLE IF NOT EXISTS items (
--                                      id      bigint generated by default as identity primary key,
--                                      name        varchar(150)  not null,
--                                      description varchar(1000) not null,
--                                      available   boolean       not null,
--                                      user_id     bigint        not null
--                                          constraint fk_items_to_users
--                                              references users(id)
--                                  );

create table if not exists items
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar not null,
    description varchar not null,
    available   boolean not null,
    user_id     bigint  not null,
    constraint "items_USERS_ID_fk"
        foreign key (user_id) references USERS
)
